repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6

    hooks:
      # Run the Ruff formatter.
      - id: ruff-format
      # Run the Ruff linter.
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/ambient-innovation/boa-restrictor
    rev: v1.5.1
    hooks:
      - id: boa-restrictor
        args: [ --config=pyproject.toml ]
